/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatatanRouteImport } from './routes/catatan'
import { Route as EvaluasiRouteImport } from './routes/evaluasi'
import { Route as LatihanRouteImport } from './routes/latihan'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as PerkembanganRouteImport } from './routes/perkembangan'
import { Route as PesanRouteImport } from './routes/pesan'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as SkriningRouteImport } from './routes/skrining'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatatanRoute = CatatanRouteImport.update({
  id: '/catatan',
  path: '/catatan',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluasiRoute = EvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanRoute = LatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const PerkembanganRoute = PerkembanganRouteImport.update({
  id: '/perkembangan',
  path: '/perkembangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PesanRoute = PesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const SkriningRoute = SkriningRouteImport.update({
  id: '/skrining',
  path: '/skrining',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catatan': typeof CatatanRoute
  '/evaluasi': typeof EvaluasiRoute
  '/latihan': typeof LatihanRoute
  '/panduan': typeof PanduanRoute
  '/perkembangan': typeof PerkembanganRoute
  '/pesan': typeof PesanRoute
  '/profil': typeof ProfilRoute
  '/reward': typeof RewardRoute
  '/riwayat': typeof RiwayatRoute
  '/skrining': typeof SkriningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catatan': typeof CatatanRoute
  '/evaluasi': typeof EvaluasiRoute
  '/latihan': typeof LatihanRoute
  '/panduan': typeof PanduanRoute
  '/perkembangan': typeof PerkembanganRoute
  '/pesan': typeof PesanRoute
  '/profil': typeof ProfilRoute
  '/reward': typeof RewardRoute
  '/riwayat': typeof RiwayatRoute
  '/skrining': typeof SkriningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catatan': typeof CatatanRoute
  '/evaluasi': typeof EvaluasiRoute
  '/latihan': typeof LatihanRoute
  '/panduan': typeof PanduanRoute
  '/perkembangan': typeof PerkembanganRoute
  '/pesan': typeof PesanRoute
  '/profil': typeof ProfilRoute
  '/reward': typeof RewardRoute
  '/riwayat': typeof RiwayatRoute
  '/skrining': typeof SkriningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catatan'
    | '/evaluasi'
    | '/latihan'
    | '/panduan'
    | '/perkembangan'
    | '/pesan'
    | '/profil'
    | '/reward'
    | '/riwayat'
    | '/skrining'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catatan'
    | '/evaluasi'
    | '/latihan'
    | '/panduan'
    | '/perkembangan'
    | '/pesan'
    | '/profil'
    | '/reward'
    | '/riwayat'
    | '/skrining'
  id:
    | '__root__'
    | '/'
    | '/catatan'
    | '/evaluasi'
    | '/latihan'
    | '/panduan'
    | '/perkembangan'
    | '/pesan'
    | '/profil'
    | '/reward'
    | '/riwayat'
    | '/skrining'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatatanRoute: typeof CatatanRoute
  EvaluasiRoute: typeof EvaluasiRoute
  LatihanRoute: typeof LatihanRoute
  PanduanRoute: typeof PanduanRoute
  PerkembanganRoute: typeof PerkembanganRoute
  PesanRoute: typeof PesanRoute
  ProfilRoute: typeof ProfilRoute
  RewardRoute: typeof RewardRoute
  RiwayatRoute: typeof RiwayatRoute
  SkriningRoute: typeof SkriningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catatan': {
      id: '/catatan'
      path: '/catatan'
      fullPath: '/catatan'
      preLoaderRoute: typeof CatatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluasi': {
      id: '/evaluasi'
      path: '/evaluasi'
      fullPath: '/evaluasi'
      preLoaderRoute: typeof EvaluasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan': {
      id: '/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof LatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perkembangan': {
      id: '/perkembangan'
      path: '/perkembangan'
      fullPath: '/perkembangan'
      preLoaderRoute: typeof PerkembanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesan': {
      id: '/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof PesanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skrining': {
      id: '/skrining'
      path: '/skrining'
      fullPath: '/skrining'
      preLoaderRoute: typeof SkriningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatatanRoute: CatatanRoute,
  EvaluasiRoute: EvaluasiRoute,
  LatihanRoute: LatihanRoute,
  PanduanRoute: PanduanRoute,
  PerkembanganRoute: PerkembanganRoute,
  PesanRoute: PesanRoute,
  ProfilRoute: ProfilRoute,
  RewardRoute: RewardRoute,
  RiwayatRoute: RiwayatRoute,
  SkriningRoute: SkriningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
