/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCatatanRouteImport } from './routes/_auth/catatan'
import { Route as AuthEvaluasiRouteImport } from './routes/_auth/evaluasi'
import { Route as AuthLatihanRouteImport } from './routes/_auth/latihan'
import { Route as AuthPanduanRouteImport } from './routes/_auth/panduan'
import { Route as AuthPerkembanganRouteImport } from './routes/_auth/perkembangan'
import { Route as AuthPesanRouteImport } from './routes/_auth/pesan'
import { Route as AuthProfilRouteImport } from './routes/_auth/profil'
import { Route as AuthRewardRouteImport } from './routes/_auth/reward'
import { Route as AuthRiwayatRouteImport } from './routes/_auth/riwayat'
import { Route as AuthSkriningRouteImport } from './routes/_auth/skrining'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users.'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users.$userId'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCatatanRoute = AuthCatatanRouteImport.update({
  id: '/catatan',
  path: '/catatan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEvaluasiRoute = AuthEvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLatihanRoute = AuthLatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPanduanRoute = AuthPanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerkembanganRoute = AuthPerkembanganRouteImport.update({
  id: '/perkembangan',
  path: '/perkembangan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPesanRoute = AuthPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilRoute = AuthProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRewardRoute = AuthRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRiwayatRoute = AuthRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSkriningRoute = AuthSkriningRouteImport.update({
  id: '/skrining',
  path: '/skrining',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/catatan': typeof AuthCatatanRoute
  '/evaluasi': typeof AuthEvaluasiRoute
  '/latihan': typeof AuthLatihanRoute
  '/panduan': typeof AuthPanduanRoute
  '/perkembangan': typeof AuthPerkembanganRoute
  '/pesan': typeof AuthPesanRoute
  '/profil': typeof AuthProfilRoute
  '/reward': typeof AuthRewardRoute
  '/riwayat': typeof AuthRiwayatRoute
  '/skrining': typeof AuthSkriningRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/users/': typeof AdminAdminUsersRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/catatan': typeof AuthCatatanRoute
  '/evaluasi': typeof AuthEvaluasiRoute
  '/latihan': typeof AuthLatihanRoute
  '/panduan': typeof AuthPanduanRoute
  '/perkembangan': typeof AuthPerkembanganRoute
  '/pesan': typeof AuthPesanRoute
  '/profil': typeof AuthProfilRoute
  '/reward': typeof AuthRewardRoute
  '/riwayat': typeof AuthRiwayatRoute
  '/skrining': typeof AuthSkriningRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/catatan': typeof AuthCatatanRoute
  '/_auth/evaluasi': typeof AuthEvaluasiRoute
  '/_auth/latihan': typeof AuthLatihanRoute
  '/_auth/panduan': typeof AuthPanduanRoute
  '/_auth/perkembangan': typeof AuthPerkembanganRoute
  '/_auth/pesan': typeof AuthPesanRoute
  '/_auth/profil': typeof AuthProfilRoute
  '/_auth/reward': typeof AuthRewardRoute
  '/_auth/riwayat': typeof AuthRiwayatRoute
  '/_auth/skrining': typeof AuthSkriningRoute
  '/_auth/': typeof AuthIndexRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/catatan'
    | '/evaluasi'
    | '/latihan'
    | '/panduan'
    | '/perkembangan'
    | '/pesan'
    | '/profil'
    | '/reward'
    | '/riwayat'
    | '/skrining'
    | '/admin/'
    | '/admin/users/'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/catatan'
    | '/evaluasi'
    | '/latihan'
    | '/panduan'
    | '/perkembangan'
    | '/pesan'
    | '/profil'
    | '/reward'
    | '/riwayat'
    | '/skrining'
    | '/admin'
    | '/admin/users'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/catatan'
    | '/_auth/evaluasi'
    | '/_auth/latihan'
    | '/_auth/panduan'
    | '/_auth/perkembangan'
    | '/_auth/pesan'
    | '/_auth/profil'
    | '/_auth/reward'
    | '/_auth/riwayat'
    | '/_auth/skrining'
    | '/_auth/'
    | '/_admin/admin/'
    | '/_admin/admin/users/'
    | '/_admin/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/catatan': {
      id: '/_auth/catatan'
      path: '/catatan'
      fullPath: '/catatan'
      preLoaderRoute: typeof AuthCatatanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/evaluasi': {
      id: '/_auth/evaluasi'
      path: '/evaluasi'
      fullPath: '/evaluasi'
      preLoaderRoute: typeof AuthEvaluasiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/latihan': {
      id: '/_auth/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof AuthLatihanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/panduan': {
      id: '/_auth/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof AuthPanduanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perkembangan': {
      id: '/_auth/perkembangan'
      path: '/perkembangan'
      fullPath: '/perkembangan'
      preLoaderRoute: typeof AuthPerkembanganRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pesan': {
      id: '/_auth/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof AuthPesanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profil': {
      id: '/_auth/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthProfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reward': {
      id: '/_auth/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof AuthRewardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/riwayat': {
      id: '/_auth/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthRiwayatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/skrining': {
      id: '/_auth/skrining'
      path: '/skrining'
      fullPath: '/skrining'
      preLoaderRoute: typeof AuthSkriningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCatatanRoute: typeof AuthCatatanRoute
  AuthEvaluasiRoute: typeof AuthEvaluasiRoute
  AuthLatihanRoute: typeof AuthLatihanRoute
  AuthPanduanRoute: typeof AuthPanduanRoute
  AuthPerkembanganRoute: typeof AuthPerkembanganRoute
  AuthPesanRoute: typeof AuthPesanRoute
  AuthProfilRoute: typeof AuthProfilRoute
  AuthRewardRoute: typeof AuthRewardRoute
  AuthRiwayatRoute: typeof AuthRiwayatRoute
  AuthSkriningRoute: typeof AuthSkriningRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCatatanRoute: AuthCatatanRoute,
  AuthEvaluasiRoute: AuthEvaluasiRoute,
  AuthLatihanRoute: AuthLatihanRoute,
  AuthPanduanRoute: AuthPanduanRoute,
  AuthPerkembanganRoute: AuthPerkembanganRoute,
  AuthPesanRoute: AuthPesanRoute,
  AuthProfilRoute: AuthProfilRoute,
  AuthRewardRoute: AuthRewardRoute,
  AuthRiwayatRoute: AuthRiwayatRoute,
  AuthSkriningRoute: AuthSkriningRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
